-- MySQL Script generated by MySQL Workbench
-- Fri Oct 25 10:41:50 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ssdpy_asist
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ssdpy_asist
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ssdpy_asist` DEFAULT CHARACTER SET utf8 ;
USE `ssdpy_asist` ;

-- -----------------------------------------------------
-- Table `ssdpy_asist`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssdpy_asist`.`alumnos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `cedula` VARCHAR(45) NOT NULL,
  `telefono_alumno` VARCHAR(45) NULL,
  `fecha_nac` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `ruc` VARCHAR(45) NULL,
  `razon_social` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `nombre_ref` VARCHAR(45) NULL,
  `telefono_ref` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `foto` VARCHAR(80) NULL,
  `mama` VARCHAR(100) NULL,
  `papa` VARCHAR(100) NULL,
  `telefono_mama` VARCHAR(45) NULL,
  `telefono_papa` VARCHAR(45) NULL,
  `fecha_add` DATETIME NULL,
  `fecha_update` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ssdpy_asist`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssdpy_asist`.`cursos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `desc_corta` LONGTEXT NULL,
  `desc_detallada` LONGTEXT NULL,
  `duracion_meses` INT NULL,
  `estado` INT NULL,
  `valor_cuota` VARCHAR(45) NULL,
  `valor_matrícula` VARCHAR(45) NULL,
  `fecha_add` DATETIME NULL,
  `fecha_update` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ssdpy_asist`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssdpy_asist`.`matricula` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_alumnos` INT NOT NULL,
  `id_curso` INT NOT NULL,
  `fecha_inicio` DATE NULL,
  `valor_cuota` INT NULL,
  `valor_matricula` INT NULL,
  `fecha_add` DATETIME NULL,
  `fecha_update` DATETIME NULL,
  PRIMARY KEY (`id`, `id_alumnos`, `id_curso`),
  INDEX `id_alumnos_idx` (`id_alumnos` ASC) ,
  INDEX `fk_cursos_idx` (`id_curso` ASC) ,
  CONSTRAINT `fk_alumnos`
    FOREIGN KEY (`id_alumnos`)
    REFERENCES `ssdpy_asist`.`alumnos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursos`
    FOREIGN KEY (`id_curso`)
    REFERENCES `ssdpy_asist`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ssdpy_asist`.`grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssdpy_asist`.`grupos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `cursos_id` INT NOT NULL,
  PRIMARY KEY (`id`, `cursos_id`),
  INDEX `fk_grupos_cursos1_idx` (`cursos_id` ASC) ,
  CONSTRAINT `fk_grupos_cursos1`
    FOREIGN KEY (`cursos_id`)
    REFERENCES `ssdpy_asist`.`cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ssdpy_asist`.`horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssdpy_asist`.`horarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hora_inicio` TIME NULL,
  `hora_fin` TIME NULL,
  `dia` VARCHAR(45) NULL,
  `grupos_id` INT NOT NULL,
  `grupos_cursos_id` INT NOT NULL,
  PRIMARY KEY (`id`, `grupos_id`, `grupos_cursos_id`),
  INDEX `fk_horarios_grupos1_idx` (`grupos_id` ASC, `grupos_cursos_id` ASC) ,
  CONSTRAINT `fk_horarios_grupos1`
    FOREIGN KEY (`grupos_id` , `grupos_cursos_id`)
    REFERENCES `ssdpy_asist`.`grupos` (`id` , `cursos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ssdpy_asist`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ssdpy_asist`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `usuario` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
